spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123123
  #    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #      更新 或 创建数据表结构
      ddl-auto: update
    #      控制台 显示SQL
    show-sql: true
